#!/bin/bash

# Wait a moment to let LightDM settle after login/resume
sleep 2

# Kill any Xorg processes started by LightDM greeter
for pid in $(pgrep -x Xorg); do
    if ps -o cmd= -p "$pid" | grep -q lightdm; then
        echo "kill $pid"
        sudo kill "$pid"
    fi
done
