#!/bin/bash

swaylock \
  -f \
  --image "/usr/share/backgrounds/gundam/witchfrommercury/24話エンドカード.jpg" \
  --ignore-empty-password \
  --fade-in 1 \
  --daemonize \
  --effect-blur 3x6 \
  --indicator \
  --indicator-caps-lock \
  --clock
