#!/bin/bash

case $1 in
	pre)
		export XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
		/bin/dm-tool lock
		sleep 3
		;;
	post)
		sleep 3
		/bin/bash /home/preampinbut/.config/scripts/kill-lightdm-xorg
		;;
esac
exit 0
